import localFont from "@next/font/local";
import "./globals.css";

const bogart = localFont({
  src: [
    {
      path: "../public/fonts/bogart/Bogart-SemiBold-Italic-trial.ttf",
      style: "italic",
      weight: "600",
    },
    {
      path: "../public/fonts/bogart/Bogart-Extrabold-Italic-trial.ttf",
      style: "italic",
      weight: "800",
    },
  ],
  variable: "--font-bogart",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${bogart.variable} font-sans`}>
      <body>{children}</body>
    </html>
  );
}
